apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    app: hulk
  template:
    metadata:
      name: hulk
      labels:
        app: hulk
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
