apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    key: value
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
    matchExpressions:
    - {key: app, operator: In, values: [myapp] }
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
          - containerPort: 80