apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefull
  labels:
    app: mysql
    key: value
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
    matchExpressions:
    - {key: app, operator: In, values: [mysql] }
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
          #  value: admin123
            valueFrom:
              configMapKeyRef:
                name: my-variables
                key: password
                