apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: User
  name: suraj
  apiGroups: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: my-role
  apiGroup: rbac.authorization.k8s.io